version: '3'

services:
  db:
    image: arm64v8/mysql
    environment:
      MYSQL_DATABASE: database_development
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3009:3009"
    depends_on:
      - db
    environment:
      # Use the service name "db" as the MySQL host
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_DATABASE: database_development

volumes:
  mysql-data: